; www.conf = pool configuration file

[www]

; > by default workers run as root
user = www-data
group = www-data

; > listen on any incoming traffic on port 9000
listen = 0.0.0.0:9000

; > process management
pm = dynamic

; > num of pm(workers)
pm.start_servers = 2
pm.max_children = 5

; > idle min/max workers
pm.min_spare_servers = 1
pm.max_spare_servers = 3
