# source -> https://nginx.org/en/docs/http/ngx_http_ssl_module.html
# source -> https://cipherlist.eu/

# define which TLS versions are allowed (TLS handshake)
ssl_protocols TLSv1.2 TLSv1.3;

# client can’t downgrade security
ssl_prefer_server_ciphers on;

# which encryption algorithms (ciphers) NGINX is allowed to use
# syntax: "key exchange type"+"data encryption"
ssl_ciphers EECDH+CHACHA20:EECDH+AESGCM:EDH+AESGCM;

# create a session cashe, 10m in memory sherad with all the workers(www-data).
ssl_session_cache shared:SSL:10m;

#  cached TLS sessions live 10 minutes
ssl_session_timeout 10m;
